# ==========================================================
# Enabled Modules
# ==========================================================

KITTY_ENABLED=true

WAYBAR_ENABLED=true

WOFI_ENABLED=true

SWAYNC_ENABLED=true

HYPRLOCK_ENABLED=true

GTK_ENABLED=true

QT_ENABLED=true
