# ==========================================================
# Theme Engine Paths
# ==========================================================

THEME_ROOT="$HOME/.config/theme"

ENGINE_DIR="$THEME_ROOT/engine"

MODULES_DIR="$THEME_ROOT/modules"

RUNTIME_DIR="$THEME_ROOT/runtime"

CONFIG_DIR="$THEME_ROOT/config"

ASSETS_DIR="$THEME_ROOT/assets"

WALLPAPER_DIR="$HOME/Pictures/Wallpaper"

GENERATED_DIR="$RUNTIME_DIR/generated"

CACHE_DIR="$RUNTIME_DIR/cache"

STATE_DIR="$RUNTIME_DIR/state"

LOG_DIR="$RUNTIME_DIR/logs"
